#!/bin/bash
# Configure Prometheus for VM deployment
# This script reads .env and generates prometheus.yml with the correct API target

set -e

# Change to script directory
cd "$(dirname "$0")"

# Check if .env exists
if [ ! -f .env ]; then
    echo "Error: .env file not found!"
    echo "Please copy .env.example to .env and configure your API_HOST and API_PORT"
    echo ""
    echo "  cp .env.example .env"
    echo "  # Then edit .env with your VM IP"
    exit 1
fi

# Source environment variables
source .env

# Set defaults
API_HOST=${API_HOST:-localhost}
API_PORT=${API_PORT:-8000}
PROMETHEUS_SCRAPE_INTERVAL=${PROMETHEUS_SCRAPE_INTERVAL:-15s}

echo "Configuring Prometheus with:"
echo "  API Target: ${API_HOST}:${API_PORT}"
echo "  Scrape Interval: ${PROMETHEUS_SCRAPE_INTERVAL}"
echo ""

# Generate prometheus.yml
cat > prometheus.yml <<EOF
# Prometheus Configuration for Agent Orchestrator
# Auto-generated by configure.sh from .env settings

global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL}
  evaluation_interval: 15s
  scrape_timeout: 10s

  # Attach labels to all metrics
  external_labels:
    monitor: 'agent-orchestrator'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Agent Orchestrator API
  - job_name: 'agent-orchestrator'
    static_configs:
      - targets: ['${API_HOST}:${API_PORT}']
        labels:
          service: 'orchestrator-api'
          instance: 'local'

    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules (optional)
# rule_files:
#   - "alerts.yml"

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']
EOF

echo "✅ prometheus.yml generated successfully!"
echo ""
echo "Next steps:"
echo "  1. Start the observability stack:"
echo "     docker-compose -f ../docker-compose.observability.yml up -d"
echo ""
echo "  2. Verify Prometheus can reach your API:"
echo "     curl http://${API_HOST}:${API_PORT}/metrics"
echo ""
echo "  3. Check Prometheus targets:"
echo "     http://localhost:${PROMETHEUS_PORT:-9090}/targets"
echo ""
